    receivers:
        opencensus:
            endpoint: 0.0.0.0:55678

    processors:
        batch:
        queued_retry:
        aggregation:
            metrics:
                include:
                    match_type: strict
                    metric_names: [opdemo/process_counts, opdemo/latency]
                action: update
                
                names: [renamed/process_counts, renamed/latency]

    exporters:
        logging:
            loglevel: info
            sampling_initial: 5
            sampling_thereafter: 200
        file:
            path: ./metrics.json

    service:
        pipelines:
            traces:
                receivers: [opencensus]
                processors: [batch, queued_retry]
                exporters: [logging]
            metrics:
                receivers: [opencensus]
                processors: [aggregation]
                exporters: [file]
