    receivers:
        opencensus:
            endpoint: 0.0.0.0:55678

    processors:
        batch:
        queued_retry:
        transform:
            metric_name: opdemo/process_counts
            action: update
            new_name: transform/process_counts
            operations:
                - action: update_label
                  label: client
                  new_label: new/client
                  value_actions:
                    - value: cli
                      new_value: new/cli
                    - value: repl
                      new_value: new/repl

    exporters:
        logging:
            loglevel: info
            sampling_initial: 5
            sampling_thereafter: 200
        file:
            path: ./metrics.json

    service:
        pipelines:
            traces:
                receivers: [opencensus]
                processors: [batch, queued_retry]
                exporters: [logging]
            metrics:
                receivers: [opencensus]
                processors: [transform]
                exporters: [file]
